# ----------------------------------------------------------------------------
# Copyright (c) 2021-2026 DexForce Technology Co., Ltd.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# ----------------------------------------------------------------------------

import torch
from typing import Dict, Optional

from embodichain.lab.gym.envs import EmbodiedEnv, EmbodiedEnvCfg
from embodichain.lab.gym.utils.registration import register_env
from embodichain.utils import logger

from embodichain.lab.gym.envs.tasks.tableware.base_agent_env import BaseAgentEnv
from .action_bank import (
    ManipulatePipetteTwoBeakerActionBank,
)

__all__ = [
    "ManipulatePipetteTwoBeakerEnv",
    "ManipulatePipetteTwoBeakerTestEnv",
    "ManipulatePipetteTwoBeakerAgentEnv",
]


@register_env("ManipulatePipetteTwoBeaker", max_episode_steps=600)
class ManipulatePipetteTwoBeakerEnv(EmbodiedEnv):
    def __init__(self, cfg: EmbodiedEnvCfg = None, **kwargs):
        super().__init__(cfg, **kwargs)

        action_config = kwargs.get("action_config", None)
        if action_config is not None:
            self.action_config = action_config

        self._pipette_min_reach_count = torch.zeros(
            self.num_envs, dtype=torch.int32, device=self.device
        )
        self._pipette_was_at_min = torch.zeros(
            self.num_envs, dtype=torch.bool, device=self.device
        )
        self._pipette_min_tolerance = 1e-4

    def create_demo_action_list(self, *args, **kwargs):
        """
        Create a demonstration action list for the current task.

        Returns:
            list: A list of demo actions generated by the task.
        """
        logger.log_info("Create demo action list for ManipulatePipetteTask.")
        if getattr(self, "action_config") is not None:
            self._init_action_bank(ManipulatePipetteTwoBeakerActionBank, self.action_config)
            action_list = self.create_expert_demo_action_list(*args, **kwargs)
        else:
            logger.log_error("No action_config found in env, please check again.")

        if action_list is None:
            return action_list

        logger.log_info(
            f"Demo action list created with {len(action_list)} steps.", color="green"
        )
        return action_list

    def create_expert_demo_action_list(self, **kwargs):
        """
        Create an expert demonstration action list using the action bank.

        This function generates a trajectory based on expert knowledge, mapping joint and end-effector
        states to the required action format for the environment and robot type.

        Args:
            **kwargs: Additional keyword arguments.

        Returns:
            list: A list of actions, each containing joint positions ("qpos").
        """

        if hasattr(self, "action_bank") is False or self.action_bank is None:
            logger.log_error(
                "Action bank is not initialized. Cannot create expert demo action list."
            )

        ret = self.action_bank.create_action_list(
            self, self.graph_compose, self.packages
        )

        if ret is None:
            logger.log_warning("Failed to generate expert demo action list.")
            return None

        # TODO: to be removed, need a unified interface in robot class
        left_arm_joints = self.robot.get_joint_ids(name="left_arm", remove_mimic=True)
        right_arm_joints = self.robot.get_joint_ids(name="right_arm", remove_mimic=True)
        left_eef_joints = self.robot.get_joint_ids(name="left_eef", remove_mimic=True)
        right_eef_joints = self.robot.get_joint_ids(name="right_eef", remove_mimic=True)


        total_traj_num = ret[list(ret.keys())[0]].shape[-1]
        num_active_joints = len(self.active_joint_ids)
        actions = torch.zeros(
            (total_traj_num, self.num_envs, num_active_joints), dtype=torch.float32
        )

        # 建立一个从全局 joint_id 到 active_joint_id 在 action 数组中正确存放位置的映射
        global_to_active_idx = {
            joint_id: active_idx for active_idx, joint_id in enumerate(self.active_joint_ids)
        }

        for key, joints in [
            ("left_arm", left_arm_joints),
            ("left_eef", left_eef_joints),
            ("right_arm", right_arm_joints),
            ("right_eef", right_eef_joints),
        ]:
            if key in ret:
                # TODO: only 1 env supported now
                local_action_data = torch.as_tensor(ret[key].T, dtype=torch.float32)

                # 使用映射精准定位它在 action tensor 中的正确位置存放
                for i, joint_id in enumerate(joints):
                    if joint_id in global_to_active_idx:
                        active_idx = global_to_active_idx[joint_id]
                        actions[:, 0, active_idx] = local_action_data[:, i]
        return actions

    def is_task_success(self, **kwargs) -> torch.Tensor:
        success, _ = self._evaluate_task_state()
        return success

    def compute_task_state(self, **kwargs):
        success, fail = self._evaluate_task_state()
        return super().compute_task_state(**kwargs)

    def _initialize_episode(self, env_ids=None, **kwargs) -> None:
        super()._initialize_episode(env_ids=env_ids, **kwargs)

        if env_ids is None:
            reset_ids = torch.arange(self.num_envs, dtype=torch.long, device=self.device)
        elif isinstance(env_ids, torch.Tensor):
            reset_ids = env_ids.to(device=self.device, dtype=torch.long)
        else:
            reset_ids = torch.as_tensor(env_ids, dtype=torch.long, device=self.device)

        self._pipette_min_reach_count[reset_ids] = 0
        self._pipette_was_at_min[reset_ids] = False

    def _evaluate_task_state(self):
        beaker1 = self.sim.get_rigid_object("beaker1")
        beaker2 = self.sim.get_rigid_object("beaker2")
        pipette = self.sim.get_articulation("pipette")

        beaker1_fall = self._is_fall(beaker1.get_local_pose(to_matrix=True))
        beaker2_fall = self._is_fall(beaker2.get_local_pose(to_matrix=True))
        beaker_failed = beaker1_fall | beaker2_fall

        slide_qpos = pipette.get_qpos()[:, 0]
        slide_min = self._get_pipette_slide_min(pipette)
        at_min = slide_qpos <= 0.66 * slide_min + self._pipette_min_tolerance
        newly_reached_min = at_min & ~self._pipette_was_at_min

        self._pipette_min_reach_count += newly_reached_min.to(torch.int32)
        self._pipette_was_at_min = at_min

        # print(
        #     "[ManipulatePipette] pipette sliding joint "
        #     f"qpos={slide_qpos.detach().cpu().tolist()}, "
        #     f"min={slide_min.detach().cpu().tolist()}, "
        #     f"at_min={at_min.detach().cpu().tolist()}, "
        #     f"min_reach_count={self._pipette_min_reach_count.detach().cpu().tolist()}"
        # )

        pipette_pressed_twice = self._pipette_min_reach_count >= 2
        success = (~beaker_failed) & pipette_pressed_twice
        fail = beaker_failed

        return success, fail

    def _is_fall(self, pose: torch.Tensor) -> torch.Tensor:
        pose_rz = pose[:, :3, 2]
        world_z_axis = torch.tensor([0, 0, 1], dtype=pose.dtype, device=pose.device)
        dot_product = torch.sum(pose_rz * world_z_axis, dim=-1)
        dot_product = torch.clamp(dot_product, -1.0, 1.0)
        angle = torch.arccos(dot_product)
        return angle >= torch.pi / 4

    def _get_pipette_slide_min(self, pipette) -> torch.Tensor:
        try:
            limits = pipette.qpos_limits
        except AttributeError:
            limits = None

        if limits is None and hasattr(pipette, "body_data"):
            limits = pipette.body_data.qpos_limits

        if limits is None:
            limits = torch.as_tensor(
                [entity.get_joint_limits() for entity in pipette.entities],
                dtype=torch.float32,
                device=self.device,
            )

        limits = limits.to(device=self.device, dtype=torch.float32)
        return limits[:, 0, 0]




@register_env("ManipulatePipetteTwoBeakerTest", max_episode_steps=600)
class ManipulatePipetteTwoBeakerTestEnv(ManipulatePipetteTwoBeakerEnv):
    def compute_task_state(self, **kwargs):
        success, fail = self._evaluate_task_state()
        return success, fail, {}


@register_env("ManipulatePipetteTwoBeakerAgent", max_episode_steps=600)
class ManipulatePipetteTwoBeakerAgentEnv(BaseAgentEnv, ManipulatePipetteTwoBeakerEnv):
    def __init__(self, cfg: EmbodiedEnvCfg = None, **kwargs):
        super().__init__(cfg, **kwargs)
        super()._init_agents(**kwargs)

    def reset(self, seed: Optional[int] = None, options: Optional[Dict] = None):
        obs, info = super().reset(seed=seed, options=options)
        super().get_states()
        return obs, info
