# ----------------------------------------------------------------------------
# Copyright (c) 2021-2026 DexForce Technology Co., Ltd.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# ----------------------------------------------------------------------------

import torch
from typing import Dict, Optional, Tuple

from embodichain.lab.gym.envs import EmbodiedEnv, EmbodiedEnvCfg
from embodichain.lab.gym.utils.registration import register_env
from embodichain.utils import logger
from robosynchallenge.managers.events import visualize_rigid_body_pose
from embodichain.lab.gym.envs.tasks.tableware.base_agent_env import BaseAgentEnv
from .action_bank import (
    WaterPouringActionBank,
)

__all__ = ["WaterPouringEnv", "WaterPouringTestEnv", "WaterPouringAgentEnv"]


@register_env("WaterPouring", max_episode_steps=600)
class WaterPouringEnv(EmbodiedEnv):
    def __init__(self, cfg: EmbodiedEnvCfg = None, **kwargs):
        super().__init__(cfg, **kwargs)
        self._reset_pouring_state()

        action_config = kwargs.get("action_config", None)
        if action_config is not None:
            self.action_config = action_config

    def reset(self, seed: Optional[int] = None, options: Optional[Dict] = None):
        """Reset environment and pouring state flags."""
        obs, info = super().reset(seed=seed, options=options)
        self._reset_pouring_state()
        return obs, info

    def _reset_pouring_state(self) -> None:
        bottle_pose = self.sim.get_rigid_object("bottle").get_local_pose(to_matrix=True)
        self._initial_bottle_z = bottle_pose[:, 2, 3].clone()
        self._grasp_started = torch.zeros(
            self.num_envs, dtype=torch.bool, device=self.device
        )
        self._grasp_lost = torch.zeros_like(self._grasp_started)
        self._pouring_started = torch.zeros_like(self._grasp_started)

    def create_demo_action_list(self, *args, **kwargs):
        """
        Create a demonstration action list for the current task.

        Returns:
            list: A list of demo actions generated by the task.
        """
        logger.log_info("Create demo action list for WaterPouringTask.")

        if getattr(self, "action_config") is not None:
            self._init_action_bank(WaterPouringActionBank, self.action_config)
            action_list = self.create_expert_demo_action_list(*args, **kwargs)
        else:
            logger.log_error("No action_config found in env, please check again.")

        if action_list is None:
            return action_list

        logger.log_info(
            f"Demo action list created with {len(action_list)} steps.", color="green"
        )
        return action_list

    def create_expert_demo_action_list(self, **kwargs):
        """
        Create an expert demonstration action list using the action bank.

        This function generates a trajectory based on expert knowledge, mapping joint and end-effector
        states to the required action format for the environment and robot type.

        Args:
            **kwargs: Additional keyword arguments.

        Returns:
            list: A list of actions, each containing joint positions ("qpos").
        """

        if hasattr(self, "action_bank") is False or self.action_bank is None:
            logger.log_error(
                "Action bank is not initialized. Cannot create expert demo action list."
            )

        ret = self.action_bank.create_action_list(
            self, self.graph_compose, self.packages
        )

        if ret is None:
            logger.log_warning("Failed to generate expert demo action list.")
            return None

        # TODO: to be removed, need a unified interface in robot class
        left_arm_joints = self.robot.get_joint_ids(name="left_arm", remove_mimic=True)
        right_arm_joints = self.robot.get_joint_ids(name="right_arm", remove_mimic=True)
        left_eef_joints = self.robot.get_joint_ids(name="left_eef", remove_mimic=True)
        right_eef_joints = self.robot.get_joint_ids(name="right_eef", remove_mimic=True)


        total_traj_num = ret[list(ret.keys())[0]].shape[-1]
        num_active_joints = len(self.active_joint_ids)
        actions = torch.zeros(
            (total_traj_num, self.num_envs, num_active_joints), dtype=torch.float32
        )

        
        global_to_active_idx = {
            joint_id: active_idx for active_idx, joint_id in enumerate(self.active_joint_ids)
        }

        for key, joints in [
            ("left_arm", left_arm_joints),
            ("left_eef", left_eef_joints),
            ("right_arm", right_arm_joints),
            ("right_eef", right_eef_joints),
        ]:
            if key in ret:
                # TODO: only 1 env supported now
                local_action_data = torch.as_tensor(ret[key].T, dtype=torch.float32)

                
                for i, joint_id in enumerate(joints):
                    if joint_id in global_to_active_idx:
                        active_idx = global_to_active_idx[joint_id]
                        actions[:, 0, active_idx] = local_action_data[:, i]
        return actions

 
    def _evaluate_task_state(self) -> Tuple[torch.Tensor, torch.Tensor, Dict]:
        bottle_pose = self.sim.get_rigid_object("bottle").get_local_pose(to_matrix=True)
        cup_pose = self.sim.get_rigid_object("cup").get_local_pose(to_matrix=True)
        right_eef_pose = self.robot.get_link_pose("right_link6", to_matrix=True)

        bottle_axis = bottle_pose[:, :3, 1]
        bottle_position = bottle_pose[:, :3, 3]
        cup_position = cup_pose[:, :3, 3]
        bottle_angle = torch.acos(bottle_axis[:, 2].clamp(-1.0, 1.0))
        bottle_mouth = bottle_position + 0.236 * bottle_axis
        mouth_to_cup = cup_position - bottle_mouth

        near_gripper = (
            torch.linalg.norm(bottle_position - right_eef_pose[:, :3, 3], dim=-1) < 0.30
        )
        held = near_gripper & (
            (bottle_position[:, 2] > self._initial_bottle_z + 0.03) | self._grasp_started
        )
        relative_pose_valid = (
            (torch.linalg.norm(mouth_to_cup[:, :2], dim=-1) < 0.08)
            & (bottle_mouth[:, 2] > cup_position[:, 2] + 0.04)
            & (bottle_mouth[:, 2] < cup_position[:, 2] + 0.30)
            & (torch.sum(bottle_axis[:, :2] * mouth_to_cup[:, :2], dim=-1) > -0.02)
        )
        cup_fall = self._is_fall_z(cup_pose)
        pouring_now = (
            held
            & (bottle_angle > torch.pi / 4)
            & (bottle_angle < 2 * torch.pi / 3)
            & relative_pose_valid
            & (~cup_fall)
        )
        self._grasp_started |= held
        self._grasp_lost |= self._grasp_started & (~held)
        self._pouring_started |= pouring_now
        returned_upright = held & (bottle_angle < torch.pi / 4)
        success = (
            self._pouring_started
            & returned_upright
            & (~self._grasp_lost)
            & (~cup_fall)
        )
        metrics = {
            "bottle_angle": bottle_angle,
            "mouth_xy_dist": torch.linalg.norm(mouth_to_cup[:, :2], dim=-1),
            "held": held,
            "relative_pose_valid": relative_pose_valid,
            "pouring_now": pouring_now,
            "pouring_started": self._pouring_started.clone(),
            "grasp_lost": self._grasp_lost.clone(),
            "returned_upright": returned_upright,
            "cup_fall": cup_fall,
        }
        return success, cup_fall, metrics

    def compute_task_state(self, **kwargs):
        success, fail, metrics = self._evaluate_task_state()

        elapsed = int(self._elapsed_steps[0].item())
        if (
            elapsed % 25 == 0
            or bool(metrics["pouring_now"][0].item())
            or bool(success[0].item())
        ):
            logger.log_info(
                "[water_pouring state] "
                f"step={elapsed} "
                f"success={bool(success[0].item())} "
                f"angle_deg={float(torch.rad2deg(metrics['bottle_angle'][0]).item()):.2f} "
                f"mouth_xy={float(metrics['mouth_xy_dist'][0].item()):.5f} "
                f"held={bool(metrics['held'][0].item())} "
                f"relative_valid={bool(metrics['relative_pose_valid'][0].item())} "
                f"pouring_now={bool(metrics['pouring_now'][0].item())} "
                f"pouring_started={bool(metrics['pouring_started'][0].item())} "
                f"grasp_lost={bool(metrics['grasp_lost'][0].item())} "
                f"returned={bool(metrics['returned_upright'][0].item())} "
                f"cup_fall={bool(metrics['cup_fall'][0].item())}"
            )

        return success, fail, metrics
    
    
    def is_task_success(self, **kwargs) -> torch.Tensor:
        success, _, _ = self._evaluate_task_state()
        return success

    def _is_fall_y(self, pose: torch.Tensor) -> torch.Tensor:
        # Extract z-axis from rotation matrix (last column, first 3 elements)
        pose_rz = pose[:, :3, 1]
        world_z_axis = torch.tensor([0, 0, 1], dtype=pose.dtype, device=pose.device)

        # Compute dot product for each batch element
        dot_product = torch.sum(pose_rz * world_z_axis, dim=-1)  # Shape: (batch_size,)

        # Clamp to avoid numerical issues with arccos
        dot_product = torch.clamp(dot_product, -1.0, 1.0)

        # Compute angle and check if fallen
        angle = torch.arccos(dot_product)
        return angle >= torch.pi / 4
    def _is_fall_z(self, pose: torch.Tensor) -> torch.Tensor:
        # Extract z-axis from rotation matrix (last column, first 3 elements)
        pose_rz = pose[:, :3, 2]
        world_z_axis = torch.tensor([0, 0, 1], dtype=pose.dtype, device=pose.device)

        # Compute dot product for each batch element
        dot_product = torch.sum(pose_rz * world_z_axis, dim=-1)  # Shape: (batch_size,)

        # Clamp to avoid numerical issues with arccos
        dot_product = torch.clamp(dot_product, -1.0, 1.0)

        # Compute angle and check if fallen
        angle = torch.arccos(dot_product)
        return angle >= torch.pi / 4


@register_env("WaterPouringTest", max_episode_steps=600)
class WaterPouringTestEnv(WaterPouringEnv):
    def compute_task_state(self, **kwargs):
        _, fail, _ = self._evaluate_task_state()
        return torch.zeros(self.num_envs, dtype=torch.bool), fail, None

    def is_task_success(self, **kwargs) -> torch.Tensor:
        success, _, _ = self._evaluate_task_state()
        return torch.ones_like(success, dtype=torch.bool)

@register_env("WaterPouringAgent", max_episode_steps=600)
class WaterPouringAgentEnv(BaseAgentEnv, WaterPouringEnv):
    def __init__(self, cfg: EmbodiedEnvCfg = None, **kwargs):
        super().__init__(cfg, **kwargs)
        super()._init_agents(**kwargs)

    def reset(self, seed: Optional[int] = None, options: Optional[Dict] = None):
        obs, info = super().reset(seed=seed, options=options)
        super().get_states()
        return obs, info
